'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Script from "next/script";

import "./assets/css/bootstrap.min.css"
import "./assets/css/style.css"
import "./assets/css/responsive.css"
import "./assets/css/jquery.mCustomScrollbar.min.css"
import { useEffect, useState } from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  const [pageData, setPageData] = useState<any>();
  const [sharedComponents, setSharedComponents] = useState<any>([]);
  const [components, setComponents] = useState<any>([]);

  useEffect(() => {
    const fetchData = async () => {
      fetch("/api/home").then(res => res.json()).then(json => {
        setPageData(json);
        console.log("Layoutdata", json);
        if(json){
          setSharedComponents(json.data?.sharedPage && json.data?.sharedPage.components);
          setComponents(json.data?.page && json.data?.page.components);
        }
      });           
    }
    fetchData();
  }, []);
  return (
    <html lang="en">
      <body>          
        <Header components={sharedComponents?.Header} homeHero={components?.HomeBanner}></Header>      
        {children }      
        <Script strategy="beforeInteractive" src="js/jquery.min.js"></Script>
        <Script strategy="beforeInteractive"  src="js/popper.min.js"></Script>
        <Script strategy="beforeInteractive"  src="js/bootstrap.bundle.min.js"></Script>
        <Script strategy="beforeInteractive"  src="js/jquery-3.0.0.min.js"></Script>
        <Script strategy="beforeInteractive"  src="js/plugin.js"></Script>
        <Footer components={sharedComponents?.Footer}></Footer>     
      </body>
    </html>
  );
}
